### ISSUE TITLE
Missing Package-Requires header info

### ISSUE THREAD

**Issue by progfolio** [aviaviavi/link-preview.el#2]
See:  https://www.gnu.org/software/emacs/manual/html_node/elisp/Simple-Packages.html

You rely on the request library without declaring it as a dependency.
This will prevent certain package managers (straight.el, elpaca, etc) from being able to correctly build the package.

**Comment by aviaviavi** [comment]
@progfolio Thanks for the pointer. Should be fixed now but feel free to reopen if I missed something. As you can tell I am an elisp newb :)
