### ISSUE TITLE
Wrap preview in template

### ISSUE THREAD

**Issue by gopar** [aviaviavi/link-preview.el#4]
Would be nice if the preview was wrapped is in its own template 
Example:
some link

#+begin_preview
Preview text 
#+end_preview

With that, the preview is now clearly encapsulated and collapsible as well \o/

`org-insert-structure-template` might be a starting point if you decide this is a good idea.

**Comment by aviaviavi** [comment]
Great idea!

**Comment by gopar** [comment]
I would also say update GIF in readme
